use_frameworks!

target 'Vine_Example' do
  pod 'Vine', :path => '../'

  pod 'Sorcery'
  pod 'NSObject+Rx'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxMapKit'

  target 'VineTests' do
    inherit! :search_paths
    pod 'Vine', :path => '../'
  end
end
